apiVersion: v1
kind: PersistentVolume
metadata:
  # Change the name to match the project installation or you can leave it as generic
  name: jenkins-pv
spec:
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/jenkins

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  # The name of the project volumeClaim
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi

